spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:sqlite:${better-game-tracker.local.database-path}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-init-sql: PRAGMA foreign_keys = ON
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    placeholders:
      uuidType: BLOB

server:
  address: 0.0.0.0
  forward-headers-strategy: none
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
        same-site: strict

better-game-tracker:
  cover-directory: ${BETTER_GAME_TRACKER_COVER_DIRECTORY:${better-game-tracker.local.cover-directory}}
